### ISSUE TITLE
Melhorar visualmente a disposição das informações no carousel da seção Equipe

### ISSUE THREAD

**Issue by douglasFranco** [coronagis/site#4]
Melhorar a simetria e a responsividade dos dados exibidos nos cards do carousel.

**Comment by JacksonOsvaldo** [comment]
@douglasFranco, quando você fala de melhorar a simetria e responsividade você fala da maneira, claro, como os itens estão organizados? Você tem alguma ideia ou posso tentar melhorar o alinhamento?

**Comment by douglasFranco** [comment]
Isso, pra resoluções menores os dados ficam desalinhados, o tamanho das imagens, esse tipo de ajuste.
